In [1]:
import tensorflow as tf
import joblib
import pandas as pd
import numpy as np

# Open the Data

In [2]:
spt = pd.read_parquet('data_cleaned.parquet')

In [3]:
spt.head()

NPWP              NAMA       JNS_WP  STATUS  \
0  607109311045000     BUANG SUHARJO  OP KARYAWAN  Normal   
1  774509673045000     OKKI ANDRIANI  OP KARYAWAN  Normal   
2  248790909045000  RENOLD DARMASYAH  OP KARYAWAN  Normal   
3  901134262045000     BUZER SIAGIAN  OP KARYAWAN  Normal   
4  577730740045000     AGUS SULAIMAN  OP KARYAWAN  Normal   

                  NAMA_AR SEKSI  LAPOR 2016  LAPOR 2017  LAPOR 2018  \
0                       0     0         0.0         0.0         0.0   
1            TEGUH WIYONO     V         1.0         1.0         1.0   
2  AFRA PRAMUDYA NURJANAH    VI         1.0         1.0         1.0   
3        AHMAD IKHSANUDIN    II         0.0         0.0         0.0   
4            ENCENG HELMI   III         0.0         0.0         0.0   

   LAPOR 2019  LAPOR 2020  BENDAHARA  OP KARYAWAN  OP NON KARYAWAN      2016  \
0         0.0         0.0        0.0          1.0              0.0  0.000000   
1         1.0         1.0        0.0          1.0              0.0  0.000000   
2         1.0         1.0        0.0          1.0              0.0  0.174011   
3         0.0         0.0        0.0          1.0              0.0  0.000000   
4         1.0         0.0        0.0          1.0              0.0  0.000000   

       2017      2018      2019      2020      2021  
0  0.000000  0.000000  0.000000  0.000000  0.000000  
1  0.000000  0.000000  0.000000  0.000000  0.000000  
2 -0.041553  0.087869  0.177123 -0.059912 -0.065016  
3  0.000000  0.000000  0.000000  0.000000  0.000000  
4  0.000000  0.000000  0.000000  0.000000  0.000000

In [5]:
spt.columns

Index(['NPWP', 'NAMA', 'JNS_WP', 'STATUS', 'NAMA_AR', 'SEKSI', 'LAPOR 2016',
       'LAPOR 2017', 'LAPOR 2018', 'LAPOR 2019', 'LAPOR 2020', 'BENDAHARA',
       'OP KARYAWAN', 'OP NON KARYAWAN', '2016', '2017', '2018', '2019',
       '2020', '2021'],
      dtype='object')

In [6]:
features = ['LAPOR 2017', 'LAPOR 2018', 'LAPOR 2019', 'LAPOR 2020', 'BENDAHARA',
       'OP KARYAWAN', 'OP NON KARYAWAN', '2017', '2018', '2019',
       '2020', '2021']

In [7]:
predictor = spt[features]

In [8]:
predictor

LAPOR 2017  LAPOR 2018  LAPOR 2019  LAPOR 2020  BENDAHARA  \
0              0.0         0.0         0.0         0.0        0.0   
1              1.0         1.0         1.0         1.0        0.0   
2              1.0         1.0         1.0         1.0        0.0   
3              0.0         0.0         0.0         0.0        0.0   
4              0.0         0.0         1.0         0.0        0.0   
...            ...         ...         ...         ...        ...   
131074         1.0         1.0         1.0         1.0        0.0   
131075         1.0         1.0         1.0         1.0        0.0   
131076         0.0         0.0         0.0         1.0        0.0   
131077         0.0         0.0         0.0         0.0        0.0   
131078         0.0         1.0         1.0         1.0        0.0   

        OP KARYAWAN  OP NON KARYAWAN      2017      2018      2019      2020  \
0               1.0              0.0  0.000000  0.000000  0.000000  0.000000   
1               1.0              0.0  0.000000  0.000000  0.000000  0.000000   
2               1.0              0.0 -0.041553  0.087869  0.177123 -0.059912   
3               1.0              0.0  0.000000  0.000000  0.000000  0.000000   
4               1.0              0.0  0.000000  0.000000  0.000000  0.000000   
...             ...              ...       ...       ...       ...       ...   
131074          1.0              0.0  0.000000  0.000000  0.000000  0.000000   
131075          1.0              0.0  0.000000  0.000000  0.000000  0.000000   
131076          1.0              0.0 -0.053310 -0.032600 -0.061168 -0.059912   
131077          0.0              1.0 -0.053310 -0.032600 -0.060485 -0.059912   
131078          1.0              0.0  0.000000  0.000000  0.000000  0.000000   

            2021  
0       0.000000  
1       0.000000  
2      -0.065016  
3       0.000000  
4       0.000000  
...          ...  
131074  0.000000  
131075  0.000000  
131076 -0.064694  
131077 -0.065016  
131078  0.000000  

[131079 rows x 12 columns]

# Prediksi dengan _Extreme Gradient Boosting_

In [9]:
xgb_model = joblib.load('xgb_model.pkl')

In [11]:
xgb_preds = xgb_model.predict_proba(predictor)[:,1]
xgb_preds

array([0.13645235, 0.9017685 , 0.9117985 , ..., 0.5541775 , 0.02323023,
       0.88023317], dtype=float32)

# Prediksi dengan _Deep Neural Networks_

In [12]:
dnn_model = tf.keras.models.load_model('DNN_predictor.h5')

In [14]:
dnn_preds = tf.squeeze(dnn_model.predict(predictor.values))
dnn_preds

4097/4097 [==============================] - 7s 2ms/step


<tf.Tensor: shape=(131079,), dtype=float32, numpy=
array([0.12380596, 0.9353233 , 0.9392376 , ..., 0.67584705, 0.03857199,
       0.8976848 ], dtype=float32)>

# Ensemble Kedua Model

In [15]:
final_preds = (0.6*xgb_preds + 0.4*dnn_preds)

In [16]:
final_preds

<tf.Tensor: shape=(131079,), dtype=float32, numpy=
array([0.13139379, 0.91519046, 0.92277414, ..., 0.6028454 , 0.02936693,
       0.8872139 ], dtype=float32)>

In [17]:
spt['Prediksi Lapor SPT Tahun Pajak 2021'] = final_preds

In [18]:
spt.head()

NPWP              NAMA       JNS_WP  STATUS  \
0  607109311045000     BUANG SUHARJO  OP KARYAWAN  Normal   
1  774509673045000     OKKI ANDRIANI  OP KARYAWAN  Normal   
2  248790909045000  RENOLD DARMASYAH  OP KARYAWAN  Normal   
3  901134262045000     BUZER SIAGIAN  OP KARYAWAN  Normal   
4  577730740045000     AGUS SULAIMAN  OP KARYAWAN  Normal   

                  NAMA_AR SEKSI  LAPOR 2016  LAPOR 2017  LAPOR 2018  \
0                       0     0         0.0         0.0         0.0   
1            TEGUH WIYONO     V         1.0         1.0         1.0   
2  AFRA PRAMUDYA NURJANAH    VI         1.0         1.0         1.0   
3        AHMAD IKHSANUDIN    II         0.0         0.0         0.0   
4            ENCENG HELMI   III         0.0         0.0         0.0   

   LAPOR 2019  ...  BENDAHARA  OP KARYAWAN  OP NON KARYAWAN      2016  \
0         0.0  ...        0.0          1.0              0.0  0.000000   
1         1.0  ...        0.0          1.0              0.0  0.000000   
2         1.0  ...        0.0          1.0              0.0  0.174011   
3         0.0  ...        0.0          1.0              0.0  0.000000   
4         1.0  ...        0.0          1.0              0.0  0.000000   

       2017      2018      2019      2020      2021  \
0  0.000000  0.000000  0.000000  0.000000  0.000000   
1  0.000000  0.000000  0.000000  0.000000  0.000000   
2 -0.041553  0.087869  0.177123 -0.059912 -0.065016   
3  0.000000  0.000000  0.000000  0.000000  0.000000   
4  0.000000  0.000000  0.000000  0.000000  0.000000   

   Prediksi Lapor SPT Tahun Pajak 2021  
0                             0.131394  
1                             0.915190  
2                             0.922774  
3                             0.131394  
4                             0.247165  

[5 rows x 21 columns]

In [19]:
spt.to_csv('Prediksi Lapor Tahun Pajak 2021.csv')